using System.IO;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using DreamPoeBot.Loki.Common;
using GoBo.Infrastructure.Modules;
using log4net;

namespace GoBo.Infrastructure.Settings;

/// <summary>
///     Factory that creates settings instances by loading from JSON and
///     initializing all ISettingValue fields reflectively.
///     JSON deserialization is centralized here using BoxedValue/ValueType.
/// </summary>
[Module]
public sealed class SettingsFactory : IFactory
{
    private static readonly ILog Log = Logger.GetLoggerInstanceForType();

    internal static readonly string BasePath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
        ".dpb");

    internal static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter() }
    };

    public Type TargetType => typeof(Settings);

    public object Create(IScope scope, Type concreteType)
    {
        // 1. Create instance via Activator (default constructor)
        var settings = (Settings)Activator.CreateInstance(concreteType)!;

        // 2. Initialize any uninitialized ISettingValue fields
        InitializeValueFields(settings);

        // 3. Auto-generate descriptions for BoolValue fields
        AutoGenerateDescriptions(settings);

        // 4. Load values from JSON file if exists
        var path = GetPath(concreteType);
        LoadFromFile(settings, path);

        // 5. Wire up change events
        settings.WireEvents();

        return settings;
    }

    private static void InitializeValueFields(Settings settings)
    {
        foreach (var field in GetSettingValueFields(settings.GetType()))
        {
            // Skip if already initialized (field has default value in declaration)
            if (field.GetValue(settings) != null)
                continue;

            // Create default instance
            var instance = Activator.CreateInstance(field.FieldType);
            field.SetValue(settings, instance);
        }
    }

    private static void AutoGenerateDescriptions(Settings settings)
    {
        foreach (var field in GetSettingValueFields(settings.GetType()))
        {
            var value = field.GetValue(settings);
            if (value == null) continue;

            var valueType = value.GetType();

            // Try to set Description property if null
            var descProp = valueType.GetProperty("Description");
            if (descProp != null && descProp.CanWrite && descProp.PropertyType == typeof(string))
            {
                if (descProp.GetValue(value) == null)
                {
                    descProp.SetValue(value, FormatFieldNameAsDescription(field.Name));
                }
            }

            // Try to set Tooltip property if null
            var tooltipProp = valueType.GetProperty("Tooltip");
            if (tooltipProp != null && tooltipProp.CanWrite && tooltipProp.PropertyType == typeof(string))
            {
                if (tooltipProp.GetValue(value) == null)
                {
                    tooltipProp.SetValue(value, FormatFieldNameAsDescription(field.Name));
                }
            }
        }
    }

    private static string FormatFieldNameAsDescription(string fieldName)
    {
        // EnableAutoSave -> "Enable Auto Save"
        var sb = new StringBuilder();
        foreach (var c in fieldName)
        {
            if (char.IsUpper(c) && sb.Length > 0)
                sb.Append(' ');
            sb.Append(c);
        }
        return sb.ToString();
    }

    private static void LoadFromFile(Settings settings, string path)
    {
        if (!File.Exists(path))
            return;

        try
        {
            var json = File.ReadAllText(path);
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            foreach (var field in GetSettingValueFields(settings.GetType()))
            {
                var jsonName = JsonNamingPolicy.CamelCase.ConvertName(field.Name);
                if (!root.TryGetProperty(jsonName, out var element))
                    continue;

                var settingValue = (ISettingValue)field.GetValue(settings)!;
                try
                {
                    settingValue.ReadJson(element, JsonOptions);
                }
                catch (Exception ex)
                {
                    Log.Error($"[Settings] Failed to load field {field.Name}: {ex.Message}");
                }
            }
        }
        catch (Exception ex)
        {
            Log.Error($"[Settings] Failed to load {path}: {ex.Message}\n{ex.StackTrace}");
        }
    }

    internal static IEnumerable<FieldInfo> GetSettingValueFields(Type settingsType)
    {
        return settingsType
            .GetFields(BindingFlags.Instance | BindingFlags.Public)
            .Where(f => typeof(ISettingValue).IsAssignableFrom(f.FieldType));
    }

    internal static string GetPath(Type settingsType)
    {
        var attr = settingsType.GetCustomAttribute<SettingsAttribute>();
        var fileName = attr?.FileName ?? InferFileName(settingsType);
        return Path.Combine(BasePath, fileName);
    }

    private static string InferFileName(Type settingsType)
    {
        var name = settingsType.Name;
        if (name.EndsWith("Settings", StringComparison.Ordinal))
            name = name[..^8];
        return name.ToLowerInvariant() + ".json";
    }
}
